validate_contactForm = "//div[@class='col-md-9 col-md-offset-3']"
subject_dropdown = "//select[@name='id_contact']"
customer_service = "2"
webmaster = "1"
email_input_field_contact_form = "//label[text()='Email address']/..//following-sibling::input[@type='email']"
message_input_field_contact_form = "//textarea[@name='message']"
submit_button_contact_form = "//input[@name='submitMessage']"
submit_message_banner = "//div[@class='col-xs-12 alert alert-success']"